AWSTemplateFormatVersion: '2010-09-09'
Description: SAM Template for creating an S3 bucket

Parameters:
  Environment:
    Type: String
    Description: Environment tag for the S3 bucket (e.g., dev, prod)

Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: testing-bucket-for-ems
      Tags:
        - Key: environment
          Value: !Ref Environment
