name: 'Hello World'
description: 'Greet someone'
inputs:
  github_actor:  # id of input
    description: 'collects the github actor'
    required: true
  environment_name:
    description: 'enter the env name'
    required: true
env:
  validStgProdDeployUsers: 'madhessekar,Bharathr1,Mohamed-Kalandar-Sulaiman-S,mohammed-abbas06'
runs:
  using: "composite"
  steps:
    - name: Check if the user has permission to deploy
      if: ${{ (inputs.environment_name == 'prod' || inputs.environment_name == 'stg') && !(contains(env.validStgProdDeployUsers, github_actor)) }}
      run: |
        echo "the user does not have permission"
        exit 1
      shell: bash

