name: 'Hello World'
description: 'Greet someone'
inputs:
  environment_name:  # id of input
    description: 'enter the env_name'
    required: true


outputs:
  env_value:
    description: "Random number"
    value: ${{ steps.set_env.outputs.github_env }}
runs:
  using: "composite"
  steps:
    - name: assign env
      id: set_env
      run: |
          if echo "${{ github.event.inputs.environment_name }}" | grep -Eq '^dev[1-9]$'; then
            echo "env=dev"
            github_env="dev"
          else
            echo "env=${{ github.event.inputs.environment_name }}"
            github_env=${{ github.event.inputs.environment_name }}
          fi
          echo "github_env=$github_env" >> $GITHUB_OUTPUT
      shell: bash

