name: Restrict user Access
run-name: ${{ github.actor }} is triggered Restrict user Access job

on:
  workflow_dispatch:
    inputs:
      environment_name:
        description: 'enter the environment'
        required: true
  

# Permission can be added at job level or workflow level    
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout
  
jobs: 
  checks_user_permissions_and_assign_env:
    runs-on: ubuntu-latest
    outputs:
      env_value: ${{ steps.set_env.outputs.github_env }}
      
    steps:
    - name: Check if the user has permission to deploy
      if: ${{ (github.event.inputs.environment_name == 'prod' || github.event.inputs.environment_name == 'stg') && !(contains(${{ vars.PRODACTOR }}, github.actor)) }}
      run: |
        echo "the user does not have permission"
        exit 1

    - name: Set Environment
      id: set_env
      run: |
        if echo "${{ github.event.inputs.environment_name }}" | grep -Eq '^dev[1-9]$'; then
          echo "env=dev"
          github_env="dev"
        else
          echo "env=${{ github.event.inputs.environment_name }}"
          github_env=${{ github.event.inputs.environment_name }}
        fi
        echo "github_env=$github_env" >> $GITHUB_OUTPUT
