name: Simple 3 Jobs Workflow

on:
  workflow_dispatch:
    inputs:
      environment_name:
        description: "Target environment"
        required: true
        default: "dev"

jobs:
  approval:
    if: ${{ github.event.inputs.environment_name == 'stage' }}
    runs-on: ubuntu-latest
    outputs:
      env_value: ${{ steps.set_env.outputs.github_env }}
      
    steps:
      - name: Approval step
        id: set_env
        run: |
          echo "Approval required for stage environment."
          github_env=${{ github.event.inputs.environment_name }}
          echo "github_env=$github_env" >> $GITHUB_OUTPUT
        shell: bash

  setup-environment:
    needs: approval
    if:  ${{ (github.event.inputs.environment_name != 'stage') && always()
    runs-on: ubuntu-latest
    steps:
      - name: Setup environment
        run: |
          echo "Setting up environment: ${{ github.event.inputs.environment_name }}"

        shell: bash
        
  deploy:
    needs: setup-environment
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to environment
        run: |
          echo "Deploying to ${{ github.event.inputs.environment_name }}"
  
        shell: bash
