name: Simple 3 Jobs Workflow

on:
  workflow_dispatch:
    inputs:
      environment_name:
        description: "Target environment"
        required: true
        default: "dev"

jobs:

  decide-approval:
    runs-on: ubuntu-latest
    outputs:
      github_env: ${{ steps.decide-approval.outputs.github_env }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
    
      - name: Decide Approval based on environment
        shell: bash
        id: decide-approval
        run: |
          if echo "${{ github.event.inputs.environment_name }}" | grep -Eq 'stage'; then
            github_env="stage-approval-build-deploy" >> $GITHUB_OUTPUT
          else
            github_env=${{ github.event.inputs.environment_name }}
          fi

  approval:
    needs: decide-approval
    permissions:
        id-token: write
        contents: write
        checks: write
    environment: ${{ needs.decide-approval.outputs.github_env }}
    runs-on: ubuntu-latest
    steps:
      - name: Approval status
        shell: bash
        run: |
          echo "Change has been approved for stage monolith Deployment"
        
  deploy:
    needs: approval
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to environment
        run: |
          echo "Deploying to ${{ github.event.inputs.environment_name }}"
  
        shell: bash
