name: Simple 3 Jobs Workflow

on:
  workflow_dispatch:
    inputs:
      environment_name:
        description: "Target environment"
        required: true
        default: "dev"

jobs:
  approval:
    if: ${{ github.event.inputs.environment_name == 'stage' }}
    runs-on: ubuntu-latest
    steps:
      - name: Approval step
        run: |
          echo "Approval required for stage environment."
        shell: bash
  setup-environment:
    needs: ${{ github.event.inputs.environment_name == 'stage' && 'approval' || null }}
    runs-on: ubuntu-latest
    steps:
      - name: Setup environment
        run: |
          echo "Setting up environment: ${{ github.event.inputs.environment_name }}"

        shell: bash
        
  deploy:
    needs: setup-environment
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to environment
        run: |
          echo "Deploying to ${{ github.event.inputs.environment_name }}"
  
        shell: bash
