name: "Prod Build and Deploy"

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: write

jobs:
  assign-pods:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

    - name: Replace environment in backend.tf key
      shell: bash
      run: |
          sed -i "s#bucket    = \"iac-remote-state-tf\"#bucket    = \"my-bucket\"#" gteam_env.properties
          sed -i "s#key    = \"codedeploy_infra/int-us1.tfstate\"#key    = \"codedeploy_infra/${{ inputs.environment }}.tfstate\"#" gteam_env.properties
          sed -i "s#region    = \"us-east-1\"#region    = \"${{ inputs.terraform_state_region }}\"#" gteam_env.properties
          cat gteam_env.properties
      working-directory: .
