name: "Build and Deploy"
run-name: ${{ github.actor }} has triggered gradle build to ${{ github.event.inputs.environment_name }}


on:
  workflow_dispatch:
    inputs:
      environment_name:
        description: 'enter the environment'
        type: choice
        options:
          - int
          - qa
          - stage
        required: true

permissions:
  id-token: write
  contents: write

# Concurrency settings to prevent multiple runs
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:

  define-matrix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Get Pods
        id: get_pods
        uses: ./.github/actions/checks_permission
        with:
          environment: ${{ github.event.inputs.environment_name }}

          
  define-pod:
    runs-on: ubuntu-latest
    needs: define-matrix
    # strategy:
    #   matrix:
    #     region: ${{ fromJSON(needs.define-matrix.outputs.pods) }}
    # environment: ${{ github.event.inputs.environment_name }}-${{ matrix.region }}   # Pass the region directly here
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: test
        run: |
          echo ${{ needs.define_matrix.outputs.pods }}
        shell: bash
        
         
    
        
        
  
