name: Test Pod Deployment with Approvals

on:
  workflow_dispatch:
    inputs:
      pods:
        description: "List of pods (comma-separated)"
        required: true
        default: "pod1,pod2,pod3"

jobs:
  # Step 1: Parse Pods
  assign-pods:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get Pods
        id: get_pods
        uses: ./.github/actions/checks_permission
        with:
          environment: prod
    outputs:
      pods: ${{ steps.get_pods.outputs.pod }}

  # Step 3: Deploy Each Pod
  approval:
    needs: assign-pods
    strategy:
      matrix:
        region: ${{ fromJSON(needs.assign-pods.outputs.pod) }}
    environment: approval-${{ matrix.region }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploying ${{ matrix.pod }}
        run: |
          echo "Deploying pod: ${{ matrix.pod }}"
      - name: Capture Approval
        id: capture_approval
        run: |
          echo "Approved pod: us1"
          echo 'pod=us1' >> "$GITHUB_OUTPUT"

    outputs:
      pods: ${{ steps.capture_approval.outputs.pod }}

  # deploy-pods-ap1:
  #   needs: assign-pods
  #   environment: approval-ap1
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Capture Approval
  #       id: capture_approval
  #       run: |
  #         echo "Approved pod: ap1"
  #         echo 'pod=ap1' >> "$GITHUB_OUTPUT"

  #   outputs:
  #     pods: ${{ steps.capture_approval.outputs.pod }}
    
  deploy-notification:
    needs: approval
    runs-on: ubuntu-latest
    if: ${{ needs.approval.outputs.approved }}
    steps:
      - name: Deploying ${{ needs.approval.outputs.pods }}
        run: |
          echo "Deploying pod: ${{ needs.approval.outputs.pods }}"
