name: Test Pod Deployment with Approvals

on:
  workflow_dispatch:
    inputs:
      pods:
        description: "List of pods (comma-separated)"
        required: true
        default: "pod1,pod2,pod3"

jobs:
  # Step 1: Parse Pods
  assign-pods:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get Pods
        id: get_pods
        uses: ./.github/actions/checks_permission
        with:
          environment: prod
    outputs:
      pods: ${{ steps.get_pods.outputs.pod }}

  # Step 3: Deploy Each Pod
  deploy-pods:
    needs: assign-pods
    strategy:
      matrix:
        pod: ${{ fromJSON(needs.assign-pods.outputs.pods) }}
    environment: approval-${{ matrix.pod }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploying ${{ matrix.pod }}
        run: |
          echo "Deploying pod: ${{ matrix.pod }}"
    
  deploy-notification:
    needs: [deploy-pods,assign-pods]
    strategy:
      matrix:
          pod: ${{ fromJSON(needs.assign-pods.outputs.pods) }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploying ${{ matrix.pod }}
        run: |
          echo "Deploying pod: ${{ matrix.pod }}"
