name: "Build and Deploy"
run-name: ${{ github.actor }} has triggered gradle build to ${{ github.event.inputs.environment_name }}


on:
  workflow_dispatch:
    inputs:
      environment_name:
        description: 'enter the environment'
        type: choice
        options:
          - int
          - qa
          - stage
        required: true

permissions:
  id-token: write
  contents: write

# Concurrency settings to prevent multiple runs
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:

  define-matrix:
    runs-on: ubuntu-latest

    outputs:
      pod: ${{ steps.pod.outputs.pods }}

    steps:
      - name: Define Colors
        id: pod
        run: |
          echo 'pods=["int-us1", "int-eu1"]' >> "$GITHUB_OUTPUT"

          
  define-pod:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        region: ${{ fromJSON(needs.define-matrix.outputs.pod) }}
    environment: ${{ matrix.region }}   # Pass the region directly here
    steps:
      - name: test
        run: |
          echo ${{ vars.region}}
        shell: bash
        
         
    
        
        
  
