name: "Build and Deploy"
run-name: ${{ github.actor }} has triggered gradle build to ${{ github.event.inputs.environment_name }}


on:
  workflow_dispatch:
    inputs:
      environment_name:
        description: 'enter the environment'
        type: choice
        options:
          - int
          - qa
          - stage
        required: true

permissions:
  id-token: write
  contents: write

# Concurrency settings to prevent multiple runs
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  define-pod:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        region: ${{ fromJson('{"int": ["int-us1"], "qa": ["qa-us1", "qa-eu1"], "stg": ["stg-us1", "stg-ap1", "stg-ap2"]}')[github.event.inputs.environment] }}
    environment: ${{ matrix.region }}   # Pass the region directly here
    steps:
      - name: test
        run: |
          echo ${{ var.region}}
        shell: bash
        
         
    
        
        
  
