name: "Prod Build and Deploy"

on:
  workflow_call:
    inputs:
      version:
        description: 'The version to build and deploy'
        required: true
        type: string
  workflow_dispatch:

permissions:
  id-token: write
  contents: write

jobs:
  assign-pods:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pod: ["us1", "eu1", "ap1"]
    environment: approval-${{ matrix.pod }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set VERSION for workflow_call
        if: ${{ inputs.version != '' }}
        run: echo "VERSION=${{ inputs.version }}" >> $GITHUB_ENV

      - name: Set VERSION for workflow_dispatch
        if: ${{ inputs.version == '' }}
        run: echo "VERSION=${{ github.ref }}-${{ github.run_number }}.${{ github.run_attempt }}" >> $GITHUB_ENV

      - name: Replace environment in backend.tf key
        run: |
          echo ${{ env.VERSION }}
      - name: github run link
        run: |
          run_link="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          echo "$run_link"
        # uses: ./.github/actions/assign_env
        # with:
        #   environment: prod-us1
        #   terraform_state_bucket: my-bucket
        #   terraform_state_region: us-east-2
