name: "Prod Build and Deploy"

on:
  workflow_call:
  workflow_dispatch:

permissions:
  id-token: write
  contents: write

jobs:
  assign-pods:
    runs-on: ubuntu-latest
    environment: approval-us1
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Replace environment in backend.tf key
        uses: ./.github/actions/assign_env
        with:
          environment: prod-us1
          terraform_state_bucket: my-bucket
          terraform_state_region: us-east-2
