on:
  workflow_dispatch:
    inputs:
      env:
        description: 'enter the env_name'
        required: true

env:
  validStgProdDeployUsers: 'madhessekar,Bharathr1,mohammed-abbas06,Mohamed-Kalandar-Sulaiman-S'

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Version from Branch Name
        uses: ./.github/actions/assign_env
        with:
          ref_name: ${{ github.ref_name }}
          run_number: ${{ github.run_number }}
        id: set_version

      # - name: Check user permission
      #   uses: ./.github/actions/checks_permission
      #   with: 
      #     github_actor: ${{ github.actor }}
      #     environment_name: ${{ github.event.inputs.env }}

      # - name: Assign Environment
      #   id: set_env
      #   uses: ./.github/actions/assign_env
      #   with:
      #     environment_name: ${{ github.event.inputs.env }}

      - name: print env
        run: echo ${{ steps.set_version.outputs.version }}
