
name: Test AWS account connection 

# on:
#   push:
#     branches: [ main ]

env:
  AWS_REGION : "us-east-1"
  environment_name: 'qa'

# Permission can be added at job level or workflow level    
permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout

jobs:
  AssumeRoleAndCallIdentity:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: arn:aws:iam::455800277932:role/GithubActionsS3Access #change to reflect your IAM role’s ARN
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}

      - name: Check Environment Input
        id: env_input
        run: echo ::set-output name=environment::${{ github.event.inputs.environment }}
        continue-on-error: true  

  deploy_qa:
    runs-on: ubuntu-latest
    if: ${{ steps.env_input.outputs.environment == 'qa' }}
    steps:
      - name: Deploy to qa
        working-directory: ems-v3-v4-migration/
        run: | 
          chmod +x build_deploy.sh
          bash build_deploy.sh ${{env.environment_name}}
  deploy_prod:
    runs-on: ubuntu-latest
    if: ${{ steps.env_input.outputs.environment == 'prod' }}
    steps:
      - name: Deploy to prod
        working-directory: ems-v3-v4-migration/
        run: | 
          chmod +x build_deploy.sh
          bash build_deploy.sh ${{env.environment_name}}