name: Check tag

on:
  push:
    branches: [ main ]

permissions:
  id-token: write
  contents: write
  checks: write

jobs:
      
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set Version from Branch Name
        uses: ./.github/actions/assign_env
        with:
          ref_name: ${{ github.event.pull_request.head.ref }}
          run_number: ${{ github.run_number }}
        id: set_version
        
      - name: display output 
        shell: bash
        run: echo ${{ steps.set_version.outputs.version }}
