name: ems_po_legacy_service
run-name: ${{ github.actor }} triggered ems po legacy service stack deploy

on:
  push

permissions:
  id-token: write
  contents: read
  
env:
  region: 'us-west-2'
  prod_deploy: 'false'

jobs: 
  sam_deployment:
    runs-on: ubuntu-latest
    
    steps:
      - name: Build with Gradle    
        if: success() || failure()
        id: build_step
        run: exit 1
      
      - name: test
        if: success() || failure()
        run: |
            if echo "${{steps.build_step.outcome}}" | grep -Eq 'success'; then
              echo "build=success"
              build_status="success"
            else
              echo "build=failed"
              build_status="failed"
            fi
            echo "build_status=$build_status" >> $GITHUB_ENV
            echo $build_status
            echo "this is $build_status" 
            echo -e "\e[1m${build_status}\e[0m"
            curl --location --request POST 'https://chat.googleapis.com/v1/spaces/AAAA_pSsBgQ/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=9YXYNNZ6P56uIiO4tUnGIs00Yo4Hbb-r-8m1pbZ_j5E' \
            --header 'Content-Type: application/json' \
            --data-raw '{  
                "text": "Test execution result is: <b>'"$build_status"'</b> \n\nTest Report Link: http://d285twt4wwknu8.cloudfront.net/${{github.run_number}}/${{github.run_attempt}}/ems-test-automation-results.html",
            }'

