name: Pass Output Between Jobs

on:
  workflow_dispatch:
    inputs:
      environment_name:
        description: 'enter the environment'
        required: true

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      step1-output: ${{ steps.step1.outputs.input_env }}

    steps:
      - name: Step 1
        id: step1
        run: |
          if echo "${{ github.event.inputs.environment_name }}" | grep -Eq '^dev[1-9]$'; then
            echo "input_env=dev" 
            github_env="dev"
          else
            echo "input_env=${{ github.event.inputs.environment_name }}"
            github_env=${{ github.event.inputs.environment_name }}
          fi
          echo $gITHUB_env
        env:
          input_env: $gITHUB_env

  job2:
    needs: job1
    runs-on: ubuntu-latest

    steps:
      - name: Step 2
        run: |
          # Use the output from Job 1 in Job 2
          echo "Received output: ${{ needs.job1.outputs.step1-output }}"
