name: Check tag

on:
  push
  
permissions:
  id-token: write
  contents: write
  checks: write

jobs:
      
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: display output 
        shell: bash
        run: |
          deployment_output='{"deploymentId": "d-LH5VT18K8"}'
          deployment_id=(echo $deployment_output | jq -r '.deploymentId')
          echo "This is the $deployment_id"
          echo "DEPLOYMENT_ID=$deployment_id" >> $GITHUB_ENV
          echo "DEPLOYMENT_ID=$deployment_id" >> $GITHUB_OUTPUT
