name: ems_po_legacy_service
run-name: ${{ github.actor }} triggered ems po legacy service stack deploy

on:
  workflow_dispatch:
    inputs:
      environment_name:
        description: 'enter the environment'
        required: true
      branch_name:
        description: 'enter the bitbucket branch name'
      commit_id:
        description: 'enter bitbucket commit id'
      tag_version:
        description: 'enter the tag version'

permissions:
  id-token: write
  contents: read

env:
  proddeploy: 'test' 

jobs: 
  sam_deployment:
    runs-on: ubuntu-latest
    
    steps:
    - name: Set Environment
      if: ${{ env.proddeploy == 'true' }}
      id: set_env
      run: |
        echo $proddeploy
        if echo "${{ github.event.inputs.environment_name }}" | grep -Eq '^dev[1-9]$'; then
          echo "env=dev"
          github_env="dev"
        elif echo "${{ github.event.inputs.environment_name }}" | grep -Eq 'sw'; then
          echo "got it"
          env=${{ github.event.inputs.environment_name }}
          echo "${env//-sw}"
        else
          echo "env=${{ github.event.inputs.environment_name }}"
          github_env=${{ github.event.inputs.environment_name }}
        fi
        echo "github_env=$github_env" >> $GITHUB_OUTPUT


