name: ems_po_legacy_service
run-name: ${{ github.actor }} triggered ems po legacy service stack deploy

on:
  push

permissions:
  id-token: write
  contents: read
  
env:
  region: 'us-west-2'
  prod_deploy: 'false'
  VERSION: 0.0.${{ github.run_number }}

jobs: 
  sam_deployment:
    runs-on: ubuntu-latest
    
    steps:
      # - name: Build with Gradle    
      #   if: success() || failure()
      #   id: build_step
      #   run: exit 1
      - name: Git clone the repository
        uses: actions/checkout@v3

      - name: Set Version from Branch Name
        id: set_version
        run: |
          if echo "${{ github.ref_name }}" | grep -Eq '^release/R[0-9]+\.[0-9]+\.[0-9]+$'; then
            VERSION=$(echo "${{ github.ref_name }}" | sed -E 's/^release\/R([0-9]+\.[0-9]+\.[0-9]+)$/\1/')
            echo "VERSION=$VERSION" >> $GITHUB_ENV
          else
            echo "VERSION=0.0.${{ github.run_number }}" >> $GITHUB_ENV
          fi
          
      - name: test
        working-directory: ./ems-v3-v4-migration
        if: success() || failure()
        run: |
          for file in *; do
            if [ -f "$file" ]; then
              mkdir -p nodejs/node_modules
              cd nodejs/node_modules
              cp ../../$file .
              cd ../../
              filename=$(basename "$file" .${file##*.})
              zip "$filename.zip" "$file"
            fi
          done
          ls
          cd nodejs/node_modules/
          ls
