name: Pass Output Between Jobs

on:
  workflow_dispatch:
    inputs:
      environment_name:
        description: 'enter the environment'
        required: true

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      step1-output: ${{ steps.step1.outputs.input_env }}

    steps:
      - name: Step 1
        id: step1
        run: |
          if [[ "${{ github.event.inputs.environment_name }}" =~ ^dev[1-9]$ ]]; then
            echo "input_env=dev" >> $GITHUB_ENV
          else
            echo "input_env=${{ github.event.inputs.environment_name }}" >> $GITHUB_ENV
          fi
        env:
          input_env: $GITHUB_ENV

  job2:
    needs: job1
    runs-on: ubuntu-latest

    steps:
      - name: Step 2
        run: |
          # Use the output from Job 1 in Job 2
          echo "Received output: ${{ needs.job1.outputs.step1-output }}"
