name: Check tag

on:
  push

permissions:
  id-token: write
  contents: write
  checks: write

jobs:
      
  tags:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set Version from Branch Name
        shell: bash
        run: |
          application_name=${{ vars.APPLICATION_NAME }}
          deployment_group=${{ vars.DEPLOYMENT_GROUP }}
            # Loop through the arrays and deploy
          # Split both variables by commas
          IFS=',' read -r -a apps <<< "$application_name"
          IFS=',' read -r -a deps <<< "$deployment_group"
          for i in "${!apps[@]}"; do
            app="${apps[$i]}"
            dep="${deps[$i]}"
            echo "Deploying Application: $app - Deployment Group: $dep"
            # Insert your deployment command here
          done
