name: Pass Output Between Jobs

on:
  workflow_dispatch:
    inputs:
      environment_name:
        description: 'enter the environment'
        required: true

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      step1-output: ${{ steps.step1.outputs.output_variable }}

    steps:
      - name: Step 1
        id: step1
        run: |
          # Perform some actions in Job 1
          echo "output_variable=Hello from Job 1"
        # Set the output variable for Job 1
        env:
          output_variable: Hello from Job 1

  job2:
    needs: job1
    runs-on: ubuntu-latest

    steps:
      - name: Step 2
        run: |
          # Use the output from Job 1 in Job 2
          echo "Received output: ${{ needs.job1.outputs.step1-output }}"
