name: "Pre prod ECS Deployment"
run-name: ${{ github.actor }} has triggered ECS Deployment to ${{ github.event.inputs.environment_name }}


on:
  workflow_dispatch:
    inputs:
      environment_name:
        description: 'enter the environment'
        type: choice
        options:
          - int
          - qa
          - stage
        required: true
      service_name:
        type: choice
        options:
          - ecom
          - ecom-atcw
          - ecom-emsw
          - ecom-ems-notification
          - ecom-processor
          - ecom-plan
        description: 'enter the service name'
        required: true
      

permissions:
  id-token: write
  contents: write

jobs:

  ecs-deployment:
    runs-on: ubuntu-latest
    steps:
      
      - name: Fetch CodeDeploy Application and Deployment Group Names
        uses: ./.github/actions/fetch-codedeployment-name
        with:
          environment: ${{ github.event.inputs.environment_name }}
          service_name: ${{ github.event.inputs.service_name }}
        id: get_names

      - name: Monitor Deployment Status
        shell: bash
        run: |
          echo ${{ steps.get_names.outputs.app_name }}
          echo ${{ steps.get_names.outputs.group_name }}
