name: "Pre prod ECS Deployment"
run-name: ${{ github.actor }} has triggered ECS Deployment to ${{ github.event.inputs.environment_name }}


on:
  push:

permissions:
  id-token: write
  contents: write

jobs:

  ecs-deployment:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4
      - name: Assign CodeDeploy Names
        id: codedeploy
        uses: ./.github/actions/assign_env
        with:
          environment: stage
          service_name: ecom-atcw
      
      - name: Display Assigned Names
        run: |
          echo "Assigned Application Name: ${{ steps.codedeploy.outputs.app_name }}"
          echo "Assigned Group Name: ${{ steps.codedeploy.outputs.group_name }}"
