name: ems_po_legacy_service
run-name: ${{ github.actor }} triggered ems po legacy service stack deploy

on:
  push

permissions:
  id-token: write
  contents: read
  
env:
  region: 'us-west-2'
  prod_deploy: 'false'

jobs: 
  sam_deployment:
    runs-on: ubuntu-latest
    
    steps:
      # - name: Build with Gradle    
      #   if: success() || failure()
      #   id: build_step
      #   run: exit 1
      
      - name: test
        if: success() || failure()
        run: |
          pwd
          ls
          cd ems-v3-v4-migration/
          mkdir nodejs/
          cd nodejs
          mkdir node_modules/
          cd node_modules
          cp ../../template.yaml .
          filename=$(basename "$file" .${file##*.})
          zip "$filename.zip" "$file"
          ls
          cd nodejs/node_modules/
          ls
