name: ems_po_legacy_service
run-name: ${{ github.actor }} triggered ems po legacy service stack deploy

on:
  push

permissions:
  id-token: write
  contents: read
  
env:
  region: 'us-west-2'
  prod_deploy: 'false'

jobs: 
  sam_deployment:
    runs-on: ubuntu-latest

    steps:
      - name: test
        run: |
          echo "my branch ${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}"

