name: "Pre prod ECS Deployment"
run-name: ${{ github.actor }} has triggered ECS Deployment to ${{ github.event.inputs.environment_name }}


on:
  push:

permissions:
  id-token: write
  contents: write

jobs:

  ecs-deployment:
    runs-on: ubuntu-latest
    steps:
      
      - name: Fetch CodeDeploy Application and Deployment Group Names
        uses: ./.github/actions/fetch-codedeployment-name
        with:
          environment: int
          service_name: ecom
        id: get_names

      - name: Monitor Deployment Status
        shell: bash
        run: |
          echo ${{ steps.get_names.outputs.app_name }}
          echo ${{ steps.get_names.outputs.group_name }}
