name: Tag version

on:
  workflow_dispatch:

env:
  VERSION: 3.0.${{ github.run_number }}

concurrency:
  group: pre-prod
  cancel-in-progress: true

permissions:
  id-token: write
  contents: write
  checks: write

jobs:

  build-deploy:
    uses: ./.github/workflows/check-matrix.yaml

  tag-myjob:
    runs-on: ubuntu-latest
    needs: build-deploy
    steps:
      - uses: actions/checkout@v4
      - name: Trigger check-matrix workflow
        run: |
          echo "success"
