name: Tag version

on:
  workflow_dispatch:

env:
  VERSION: 3.0.${{ github.run_number }}

concurrency:
  group: pre-prod
  cancel-in-progress: true

permissions:
  id-token: write
  contents: write
  checks: write

jobs:

  print-version:
    runs-on: ubuntu-latest
    steps:
      - name: Print version
        run: echo ${{ env.VERSION }}
        
  build-deploy:
      uses: ./.github/workflows/check-matrix.yaml
      with:
        version: 3.0.${{ github.run_number }}
      secrets: inherit

  tag-myjob:
    runs-on: ubuntu-latest
    needs: build-deploy
    steps:
      - uses: actions/checkout@v4
      - name: check tag version matches
        run: |
          echo "3.0.${{ github.run_number }}"
