name: Tag version

on:
  push:
    branches: [ main ]

env:
  VERSION: 3.0.${{ github.run_number }}

concurrency:
  group: pre-prod

permissions:
  id-token: write
  contents: write
  checks: write

jobs:
      
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

  build-deploy:
    uses: ./.github/workflows/check-matrix.yaml

  tag-myjob:
    runs-on: ubuntu-latest
    needs: build-deploy
    steps:
      - uses: actions/checkout@v4
      - name: Trigger check-matrix workflow
        run: |
          echo "success"
