name: Tag version

on:
  push:
    branches: [ main ]

env:
  VERSION: 3.0.${{ github.run_number }}

concurrency:
  group: pre-prod

permissions:
  id-token: write
  contents: write
  checks: write

jobs:
      
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Trigger check-matrix workflow
        uses: ./.github/workflows/check-matrix.yaml

      # - name: Trigger check-matrix workflow
      #   run: |
      #     gh workflow run check-matrix.yaml --ref main
      #   env:
      #     GH_TOKEN: ${{ secrets.BOT_PAT }}


