name: test version

on:
  push

jobs:
  test-version:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: test job
        uses: ./.github/actions/assign-env
        with:
          environment: dev
        
